In [15]:
import numpy as np

In [16]:
skaler=np.array(90)
print (skaler)

90


In [17]:
vektor=np.array([1,2,3,4,5,6])
print (vektor)

[1 2 3 4 5 6]


In [18]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (matris)  

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
tensor=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]) 
print (tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
